[global]
Tweet_limit = 100
Tweet_id_buffer = 100
Interval_pattern = [ 1.0, 2.5, 4.0,]
Support_Muiltibyte = true

[APIkeys]
API_Key = "heluc4EBrGzVbtvRPbBM3UcC0"
API_Key_Secret = "1nJf1sBLWZWX2Ez76WhgMgQTEnYUFKMN4YSBKodLxjDvbCP8hh"
Accsess_Token = "216580403-DG7jHBcwok9F00gk2CXVxU0ewiIrukedtKfEEC4h"
Accsess_Token_Secret = "BITGeFf5vhWHx8B4LfCYtfZCNNirxay9sHJm5lKx1vEFs"
